version: "3.8"

services:
  rtsp-grid:
    image: ivision/multi-axis-stream:dev
    build: .
    ports:
      - "13000:3000"
      - "10000-10030:10000-10030"
    volumes:
      - ./cameras.json:/app/cameras.json
    privileged: true
    restart: unless-stopped
