version: "3.8"

services:
  rtsp-grid:
    image: ivision/multi-axis-stream:dev
    build: .
    environment:
      - PORT=${PORT:-3000}
      - BASE_WS_PORT=${BASE_WS_PORT:-52000}
    ports:
      - "127.0.0.1:13000:3000"
      - "127.0.0.1:52000-52030:52000-52030"
    volumes:
      - ./cameras.json:/app/cameras.json
    privileged: true
    restart: unless-stopped
